name: 10 - Functions
on:
    pull_request:
    workflow_dispatch:
      inputs:
        env_selector:
          description: "enviroment selector"
          type: environment
          required: true

jobs:
    demo:
      runs-on: ubuntu-latest
      environment: ${{ inputs.env_selector }}
      steps:
        - name: Failing step
          run: |
            exit 1
        - name: Run on failure
          if: failure()
          run: echo "This step runs only if the previous step failed."
        - name: Always run step
          if: always()
          run: echo "This step runs regardless of the previous step's outcome."
        - name: Run on success
          if: success()
          run: echo "This step runs only if the previous step succeeded."
        - name: Bug step
          if: ${{contains(github.event.pull_request.title, 'fix')}}
          run: echo "This step runs only if the pull request title contains 'fix'."
