name: 17 - 3 - Custom Actions - JS

run-name: "17 - 3 - Custom Actions - JS - Base: ${{ inputs.base-branch }} - Target: ${{ inputs.target-branch }} - Dir: ${{ inputs.working-directory }}"

on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'The branch used as the base for the dependency update checks.'
        default: main
        required: false
      target-branch:
        description: 'The branch from which the PR is created.'
        default: update-dependencies
        required: false
      working-directory:
        description: 'The working directory of the project to check for dependency updates.'
        required: true
        default: 17-custom-actions/my-app
      debug:
        description: 'Whether the output debug messages to the console.'
        required: false

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
        with:
          base-branch: main
          target-branch: update-dependencies
          working-directory: 17-custom-actions/my-app
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          debug: ${{ inputs.debug }}
