name: 17 - 6 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: false
        default: 'World'

jobs:
  hello-to-you-docker:
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.hello-to-you-step.outputs.time }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Hello to You
        id: hello-to-you-step
        uses: ./.github/actions/hello-to-you-docker
        with:
          name: ${{ inputs.name }}

  get-the-time:
    runs-on: ubuntu-latest
    needs: hello-to-you-docker
    steps:
      - name: Get the time from the Docker action output
        run: |
          echo "The time we greeted you was: ${{ needs.hello-to-you-docker.outputs.time }}"            
