name: 18 - 1 - Managing Concurrency
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-slow-greet
  cancel-in-progress: true
jobs:
  slow-greet:
    runs-on: ubuntu-latest
    steps:
      - name: Slow Greet
        run: |
          echo "Hello, this is a slow greeting!"
          sleep 30
